blank_issues_enabled: false
contact_links:
  - name: Catalyst community on Discord
    url: https://discord.gg/n8tGJ6Rn6D
    about: Please ask and answer questions here.
  - name: Catalyst community on Matrix
    url: https://matrix.to/#/#catalyst-editor:matrix.org
    about: Please ask and answer questions here.
  - name: Catalyst documentation
    url: https://docs.catalyst.dev/
    about: Documentation for Catalyst
